config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get 'about', to: 'pages#about'

  devise_for :admins

  mount Ckeditor::Engine => '/ckeditor'

  resources :posts
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  # Validations
  validates :title, presence: true, length: { maximum: 150 }
  validates :summary, presence: true, length: { maximum: 300 }
  validates :body, presence: true, length: { maximum: 500_000 }


  mount_uploader :cover_image, ImageUploader
  validates :cover_image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[edit update show destroy]
  before_action :authenticate_admin!, except: %i[index show]

  # Index action to render all posts
  def index
    @posts = Post.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 8)
  end

  # New action for creating post
  def new
    @post = Post.new
  end

  # Create action saves the post into database
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = 'Successfully created post!'
      redirect_to post_path(@post)
    else
      flash[:alert] = 'Error creating new post!'
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit; end

  # Update action updates the post with the new information
  def update
    if @post.update_attributes(post_params)
      flash[:notice] = 'Successfully updated post!'
      redirect_to post_path(@posts)
    else
      flash[:alert] = 'Error updating post!'
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
    @featured_posts = Post.all.shuffle.take(7)
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if @post.destroy
      flash[:notice] = 'Successfully deleted post!'
      redirect_to posts_path
    else
      flash[:alert] = 'Error updating post!'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :meta_tag, :summary, :cover_image)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_navigation.html.erb
<nav id="tf-menu" class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Supreme Website Content', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Articles', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <% if admin_signed_in? %>
          <!--This block is only visible to signed in admins -->
          <li><%= link_to 'Logout', destroy_admin_session_path, :method => :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Supreme Website Content</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<body>
  <!-- Render navigation bar -->
  <%= render "layouts/navigation" %>

  <% if notice %>
    <div class="container alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="container alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= alert %>
    </div>
  <% end %>


  <%= yield %>


  <nav class="bottom-footer">
    <div class="container">
      
      <p class="copyright-txt">
        © 2017 Supreme Website Content | All rights reserved
      </p>

    </div>
  </nav>


</body>
</html>

app/views/pages/about.html.erb
<div id="tf-page-header" class="layout-two text-center">
  <div class="container">
    <h5><em>Thanks for visiting!</em></h5>
    <hr>
    <h2 class="text-uppercase">About Supreme Website Content</h2>
  </div>
</div>

<div id="tf-content" class="about">
  <div class="container">
    <!-- Container -->
    <div class="row">
      <!-- Row -->
      <div class="col-md-10 col-md-offset-1">
        <!-- About us content -->
        <div class="post-block">
          <div class="post-detail text-center">
            <p>Quisque at nisl lacinia, pretium neque et, volutpat urna. In in lobortis nisl, sed vehicula tortor. Fusce congue fermentum imperdiet. Ut convallis turpis nec justo suscipit, vel porta ante porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam eleifend nulla erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec purus arcu, scelerisque at scelerisque ac, interdum vel lectus. Mauris eget tortor nec lectus volutpat pellentesque non non massa. Pellentesque tempus in diam at pharetra. Integer ultricies consequat dolor. Suspendisse potenti. Vivamus id lobortis eros. Ut in scelerisque nisl. Maecenas lacinia neque ac placerat iaculis. Morbi sollicitudin rutrum maximus.</p>

            ula. Maecenas velit orci, luctus pulvinar efficitur nec, feugiat et mi.</p>
        </div>
      </div>
      <!-- endAbout us content -->
    </div>
    <!-- end Row -->
  </div>
  <!-- End Container -->
</div>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1">

    <%= simple_form_for @post do |f| %>
      <% if @post.errors.any? %>
        <div class="col-xs-12 text-center alert alert-warning" id="error_explanation" role="alert">
          <h2>
            <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
          </h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li>
                <%= msg %>
              </li>
              <% end %>
          </ul>
        </div>
      <% end %>

      <br />

      <div class="file-field input-field">
        <%= f.label :cover_image %><br/>
        <%= f.file_field :cover_image, accept: 'image/jpeg,image/gif,image/png' %>
        <br>
      </div>

      <div class="form-group">
        <%= f.input :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :summary %><br/>
        <%= f.text_area :summary, rows: 5, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :meta_tag %><br/>
        <%= f.text_area :meta_tag, rows: 2, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.button :submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<!--Date of Review-->
<a href="#" class="meta-date">
  <span class="bolder"><%= post.created_at.strftime("%d") %></span>
  <%= post.created_at.strftime("%b") %>
</a>

<!--Review Title-->
<h2><%= link_to post.title, post_path(post) %></h2>

<!--Review Image and Tag Lines-->
<div class="img-wrap text-center">
  <%= link_to image_tag(post.cover_image, class: "img-responsive"), post_path(post) %>
</div>

<!-- Author Information -->
<div class="author-box">
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">Written by James</h4>
    </div>
  </div>
</div>

<!--Product Shop and Address-->
<h5 class="text-center">Reviewed from <%= post.city %>, <%= post.country %>.</h5>
<hr>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render "posts/form" %>

app/views/posts/index.html.erb
<!-- Headline -->
<div id="tf-page-header" class="layout-two text-center">
  <div class="container">
    <h5><em>Articles</em></h5>
    <hr>
  </div>
</div>

<div id="tf-content" class="layout-two">
  <div class="container">
    <!-- New Post Link -->
    <div class="col-md-6 col-md-offset-3">
      <% if admin_signed_in? %>
        <%= link_to 'New Blog Post', new_post_path, class: 'btn btn-default btn-block tf-btn color' %>
      <% end %>
    </div>

     <div class="row container col-sm-12 text-center pagination">
      <%= will_paginate @posts %>
    </div>

    <div class="row">
      <% @posts.each do |post| %>
        <%= link_to post_path(post) do %>
          <div class="col-md-8 col-md-offset-2">
            <div class="blog-post">
              <div class="post-detail">
                <div class="img-wrap text-center">
                  <%= image_tag(post.cover_image, class: "img-responsive") %>
                </div>
                <h2><%= post.title %></h2>
                <a href="#" class="meta-date">
                  <span class="bolder"><%= post.created_at.strftime("%d") %></span>
                  <%= post.created_at.strftime("%b") %>
                </a>

                <p><%= post.summary %></p>
                
                <% if admin_signed_in? %>
                  <%= link_to "Edit", edit_post_path(post), class: "btn btn-default" %>
                  <%= link_to "Delete", post_path(post), class: "btn btn-danger", data: {:confirm => "Are you sure?"}, method: :delete %>
                <% end %>
                <hr />
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h2 class="text-center">Create New Post</h2>

<%= render "posts/form" %>

app/views/posts/show.html.erb
<!-- Headline -->
<div id="tf-page-header" class="layout-two text-center">
  <div class="container">
    <h5><em>Article</em></h5>
    <hr>
  </div>
</div>

<div id="tf-content" class="layout-two">
  <div class="container">
    <div class="row">

      <div class="col-md-8">
        <div class="blog-post">
          <div class="post-detail">
            
            <!--Date of Review-->
            <a href="#" class="meta-date">
              <span class="bolder"><%= @post.created_at.strftime("%d") %></span>
              <%= @post.created_at.strftime("%b") %>
            </a>

            <!--Review Title-->
            <h2><%= link_to @post.title, post_path(@post) %></h2>

            <!--Review Image and Tag Lines-->
            <div class="img-wrap text-center">
              <%= link_to image_tag(@post.cover_image, class: "img-responsive"), post_path(@post) %>
            </div>

            <!-- Author Information -->
            <div class="author-box">
              <div class="media">
                <div class="media-body">
                  <h4 class="media-heading">Written by James Njine</h4>
                </div>
              </div>
            </div>

          
            <!--Post Body-->
            <div class="post-content">
              <%= raw(@post.body) %>
            </div>
          </div>

          <!-- Edit and Delete Buttons -->
          <% if admin_signed_in? %>
            <%= link_to "Edit this Post", edit_post_path(@post), class: "edit-btn" %>
            <%= link_to "Delete this Post", post_path, method: :delete, 
                                                data: { confirm: "Are you sure you want to delete this post?" }, 
                                                class: "delete-btn" %>
          <% end %>
        

        </div>
          <div class="text-center">    
            <%= link_to "Back to All Posts", posts_path, class: 'btn btn-default btn-block tf-btn color' %> 
          </div>
      </div>

      <div class="col-md-4">
        <div class="sidebar">
          <div class="widget recent">
            <h4>Recent Posts</h4>
            <div class="widget-wrap">
              <% @featured_posts.each do |post| %>
                <div class="thumb-post">
                  <%= link_to post_path(post) do %>
                    <div class="info">
                      <h3 class="media-heading"><%= post.title %></h3>
                       <%= image_tag(post.cover_image, class: "img-responsive") %>
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>